package com.example.dayvee.ui.common

import com.example.dayvee.R
import com.example.dayvee.domain.model.TaskIcon

object TaskIcons {
    val defaultIcons: List<TaskIcon.Resource> = listOf(
        TaskIcon.Resource(R.drawable.icon_alarm),
        TaskIcon.Resource(R.drawable.icon_bag),
        TaskIcon.Resource(R.drawable.icon_bookmark),
        TaskIcon.Resource(R.drawable.icon_bookmark_outline),
        TaskIcon.Resource(R.drawable.icon_bookmark_solid),
        TaskIcon.Resource(R.drawable.icon_book),
        TaskIcon.Resource(R.drawable.icon_camera),
        TaskIcon.Resource(R.drawable.icon_chat),
        TaskIcon.Resource(R.drawable.icon_checked_box),
        TaskIcon.Resource(R.drawable.icon_clipboard),
        TaskIcon.Resource(R.drawable.icon_clock),
        TaskIcon.Resource(R.drawable.icon_cloud),
        TaskIcon.Resource(R.drawable.icon_contacts),
        TaskIcon.Resource(R.drawable.icon_current_location),
        TaskIcon.Resource(R.drawable.icon_desktop),
        TaskIcon.Resource(R.drawable.icon_diamond),
        TaskIcon.Resource(R.drawable.icon_document),
        TaskIcon.Resource(R.drawable.icon_download),
        TaskIcon.Resource(R.drawable.icon_dribbble),
        TaskIcon.Resource(R.drawable.icon_edit),
        TaskIcon.Resource(R.drawable.icon_envelope),
        TaskIcon.Resource(R.drawable.icon_fire),
        TaskIcon.Resource(R.drawable.icon_flask),
        TaskIcon.Resource(R.drawable.icon_gamepad),
        TaskIcon.Resource(R.drawable.icon_headset),
        TaskIcon.Resource(R.drawable.icon_heartbeat),
        TaskIcon.Resource(R.drawable.icon_image),
        TaskIcon.Resource(R.drawable.icon_instagram),
        TaskIcon.Resource(R.drawable.icon_lightbulb),
        TaskIcon.Resource(R.drawable.icon_lightning),
        TaskIcon.Resource(R.drawable.icon_microphone),
        TaskIcon.Resource(R.drawable.icon_mobile_phone),
        TaskIcon.Resource(R.drawable.icon_phone),
        TaskIcon.Resource(R.drawable.icon_present),
        TaskIcon.Resource(R.drawable.icon_printer),
        TaskIcon.Resource(R.drawable.icon_shopping_bag),
        TaskIcon.Resource(R.drawable.icon_shopping_cart),
        TaskIcon.Resource(R.drawable.icon_telegram),
        TaskIcon.Resource(R.drawable.icon_twitter),
        TaskIcon.Resource(R.drawable.icon_umbrella),
        TaskIcon.Resource(R.drawable.icon_university),
        TaskIcon.Resource(R.drawable.icon_user_plus),
        TaskIcon.Resource(R.drawable.icon_viber),
        TaskIcon.Resource(R.drawable.icon_whatsapp),
        TaskIcon.Resource(R.drawable.icon_windows),
        TaskIcon.Resource(R.drawable.icon_youtube),
    )
}